### PR TITLE
First stab at iot-device nodes that follow node-red best practices

### PR DESCRIPTION
**Pull request by pierreca**
Executing the plan outlined here: 
https://github.com/Azure/azure-iot-sdk-node/wiki/NodeRedSupport
See readme included with the PR

Kinda works:
- per-device config node
- telemetry (D2C)
- commands (C2D)
- direct methods

Still todo (in an iteration or a subsequent PR):
- use credentials on the config node (right now I rely on an environment variable which will prevent using multiple devices in the same node-red instance
- support for D2C and C2D message properties as proper inputs and outputs.
- twin feature
- file upload feature
- proper docs
- tests

### CODE REVIEW

**Comment by pierreca** [comment]
@rasavant-ms  files are there - I'm guessing it might have to do with permissions to see my fork. I've added you as a contributor, please let me know if that fixes it!

**Comment by rasavant-ms** [comment]
@pierreca - I do see them now. Thank you!

**Comment by pierreca** [comment]
good! is this going to be merged ? i see it closed but not merged - any changes needed?

**Comment by rasavant-ms** [comment]
This has been merged 😄

**Comment by rasavant-ms** [comment]
I did see the changes reflected after I used the "git pull <branch>" and "git merge --no-ff <branch>" commands. Let me try re-opening the pull request and trying this again.

**Comment by rasavant-ms** [comment]
@pierreca I wasn't able to re-open the PR. Maybe you can, since you created it.
Will give merging the PR another shot.

**Pull request closed without merging**
